/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.wurstworks.folio.app;

import org.wurstworks.folio.utilities.list.LinkedList;

import static org.wurstworks.folio.utilities.StringUtils.join;
import static org.wurstworks.folio.utilities.StringUtils.split;
import static org.wurstworks.folio.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
