/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.wurstworks.folio.app;

class MessageUtils {
    public static final String MESSAGE = "Hello World!";

    public static String getMessage() {
        return MESSAGE;
    }
}
