/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.wurstworks.folio.app;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

import org.junit.jupiter.api.Test;

public class MessageUtilsTest {
    @Test
    public void testGetMessage() {
        assertThat(MessageUtils.getMessage()).isEqualTo(MessageUtils.MESSAGE);
    }
}
